// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: squareadder.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SquareAdderClient is the client API for SquareAdder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquareAdderClient interface {
	SquareAdd(ctx context.Context, in *SquareAddRequest, opts ...grpc.CallOption) (*SquareAddResponse, error)
}

type squareAdderClient struct {
	cc grpc.ClientConnInterface
}

func NewSquareAdderClient(cc grpc.ClientConnInterface) SquareAdderClient {
	return &squareAdderClient{cc}
}

func (c *squareAdderClient) SquareAdd(ctx context.Context, in *SquareAddRequest, opts ...grpc.CallOption) (*SquareAddResponse, error) {
	out := new(SquareAddResponse)
	err := c.cc.Invoke(ctx, "/SquareAdder/SquareAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquareAdderServer is the server API for SquareAdder service.
// All implementations must embed UnimplementedSquareAdderServer
// for forward compatibility
type SquareAdderServer interface {
	SquareAdd(context.Context, *SquareAddRequest) (*SquareAddResponse, error)
	mustEmbedUnimplementedSquareAdderServer()
}

// UnimplementedSquareAdderServer must be embedded to have forward compatible implementations.
type UnimplementedSquareAdderServer struct {
}

func (UnimplementedSquareAdderServer) SquareAdd(context.Context, *SquareAddRequest) (*SquareAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareAdd not implemented")
}
func (UnimplementedSquareAdderServer) mustEmbedUnimplementedSquareAdderServer() {}

// UnsafeSquareAdderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquareAdderServer will
// result in compilation errors.
type UnsafeSquareAdderServer interface {
	mustEmbedUnimplementedSquareAdderServer()
}

func RegisterSquareAdderServer(s grpc.ServiceRegistrar, srv SquareAdderServer) {
	s.RegisterService(&SquareAdder_ServiceDesc, srv)
}

func _SquareAdder_SquareAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquareAdderServer).SquareAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SquareAdder/SquareAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquareAdderServer).SquareAdd(ctx, req.(*SquareAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquareAdder_ServiceDesc is the grpc.ServiceDesc for SquareAdder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquareAdder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SquareAdder",
	HandlerType: (*SquareAdderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SquareAdd",
			Handler:    _SquareAdder_SquareAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "squareadder.proto",
}
